### ISSUE TITLE
[BUG] Mark as read example in Wiki doesn't work

### ISSUE THREAD

**Issue by blmayer** [filipporomani/whatsapp#18]
I get the error:

`Message.__init__() got an unexpected keyword argument 'id'`

**Comment by filipporomani** [comment]
Thanks for reporting this!!
I'll fix this up asap, probably tomorrow!

**Comment by filipporomani** [comment]
Fixed in v3.0.3. Just update the library with ``pip install --upgrade whatsapp-python `` and everything should work. Let me know if there is any more problem regarding this! You can repoen the issue if it persists! 

Thanks a lot!!
