### ISSUE TITLE
[BUG] Error with fastapi

### ISSUE THREAD

**Issue by pptx704** [filipporomani/whatsapp#22]
**Describe the bug**
I am getting the following error-
```
Traceback (most recent call last):
  File "/path/to/directory/main.py", line 13, in <module>
    app.run()
  File "/path/to/env/pypoetry/virtualenvs/app-5rTTtjLO-py3.11/lib/python3.11/site-packages/whatsapp/__init__.py", line 181, in run
    self.app.run(host=host, port=port, debug=debug, **options)
    ^^^^^^^^^^^^
AttributeError: 'FastAPI' object has no attribute 'run'
```

**To Reproduce**
Copypaste the code for event listener from the [wiki](https://github.com/filipporomani/whatsapp/wiki/App-events) and run it.

**Expected behavior**
App server should run

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Additional Context**
I installed it using poetry. Currently this issue can be fixed by defining the run function as following-

```python
def run(self, host: str = "localhost", port: int = 5000, *args, **options):
    # self.app.run(host=host, port=port, debug=debug, **options)
    uvicorn.run(self.app, host=host, port=port, *args, **options)
```

If relevant, I am also getting `AttributeError: 'Message' object has no attribute 'instance'` and `AttributeError: 'Whatsapp' object has no attribute 'instance'` everywhere

**Comment by filipporomani** [comment]
Thanks for reporting! Fixed the error in [c42ebf5](https://github.com/filipporomani/whatsapp/commit/c42ebf552ed6899e7a794f07423517ee342ef095) and published new release to PyPi!
