### ISSUE TITLE
[BUG] 'Message' object has no attribute 'url'

### ISSUE THREAD

**Issue by pptx704** [filipporomani/whatsapp#25]
**Describe the bug**
Trying to reply to a message using `message.reply()`

```python
/path/to/env/lib/python3.11/site-packages/whatsapp/ext/_message.py", line 60, in reply
    r = requests.post(self.url, headers=self.headers, json=payload)
                      ^^^^^^^^
AttributeError: 'Message' object has no attribute 'url'
```

**To Reproduce**
```python
@app.on_message
async def on_message(message):
    question = message.content
    await message.reply(question)
```

**Expected behavior**
Message sent properly

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 22.04
 - Package Manager: Poetry
 - Python: 3.11

**Additional Context**
I made a small patch for the previously reported bug to progress further and stumbled upon this.

**Comment by pptx704** [comment]
There are way too many errors. Can you test all methods (at least the basic message receive and reply methods) before making new release?

**Comment by filipporomani** [comment]
Hello, thanks again for reporting. I'm very sorry for the issues. I'll check and test the library ASAP. My apologies
