### ISSUE TITLE
[BUG] requirements not declared by default

### ISSUE THREAD

**Issue by SurajBhari** [filipporomani/whatsapp#28]
**Describe the bug**
just doing `pip install whatsapp-python` doesn't make it run. and can be misleading for new developers who don't know what is wrong. 

**To Reproduce**
1. make a new enviorement. 
2. `pip install whatsapp-python`
3. try using it by importing it and get ModuleNotFoundError

**Expected behavior**
it should have installed 
- `fastapi`
- `uvicorn`
- `requests_toolkit`

**Additional context**
just adding a requirements.txt and stating it in setup.py should work.

**Comment by filipporomani** [comment]
Fixed - updated pyproject.toml

Thanks for reporting!!

**Comment by SurajBhari** [comment]
hey @filipporomani i accidentally called it `requests_toolkit` while it is `requests_toolbelt` :yikes:

**Comment by filipporomani** [comment]
😂 no prob I'll fix this up

**Comment by SurajBhari** [comment]
@filipporomani i had a question i am trying to run the webhook example. but the issue is the `data` given by the api if passed to Message class in data attribute. will give a broken object. where simple stuff like message.sender is None. is this expected behavour ? cuz i don't think so//

**Comment by SurajBhari** [comment]
on doing some debugging i found a mistake in this line https://github.com/filipporomani/whatsapp/blob/3c04097af9802594d1ddf479abaaadfb662ece65/whatsapp/__init__.py#L243

the self.instance = instance should be way above as self.instance is being utilized above. and it will throw an error f'ing up everything and making everything None.

**Comment by SurajBhari** [comment]
I will make PR to fix it all xD
